/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.net.URL;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import sortingrobot.Matriz;

/**
 *
 * @author Usuario Asus
 */
public class Resultados extends javax.swing.JFrame {

    /**
     * Creates new form Resultados
     */
    Vector<String> ruta;
    private ImageIcon arregloDeImagenes[] = new ImageIcon[4];
    private PintarfondoCeldas movimientos[][]; //Matriz de Jlabel
    int limite = 0, filas = 0, columnas = 0;

    public Resultados(Vector<String> ruta, int tamanoSolucion) {
        initComponents();
        this.ruta = ruta;
        limite = tamanoSolucion;
        obtenerFilasColumnas(limite);
        crearTablero(ruta);
    }

    private void obtenerFilasColumnas(int tamano) {
        if (tamano <= 10) {
            filas = 1;
            columnas = tamano;
        }else{
            columnas= 10;
            filas = (int) Math.ceil(tamano/10);
        }
    }

    private Icon retornarMovimiento(String movimiento) {
        if (movimiento.equalsIgnoreCase("arriba")) {
            return arregloDeImagenes[0];
        } else if (movimiento.equalsIgnoreCase("abajo")) {
            return arregloDeImagenes[1];
        } else if (movimiento.equalsIgnoreCase("izquierda")) {
            return arregloDeImagenes[2];
        } else if (movimiento.equalsIgnoreCase("derecha")) {
            return arregloDeImagenes[3];
        }
        return null;
    }

    public void crearTablero(Vector<String> ruta) {
        panelResultado.removeAll();
        panelResultado.setLayout(new GridLayout(filas, 10));

        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                movimientos[i][j].setIcon(retornarMovimiento(ruta.elementAt(i+j)));
                movimientos[i][j].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                movimientos[i][j].setBorder(BorderFactory.createLineBorder(Color.black));
                movimientos[i][j].setFont(new Font("Arial", 1, 12));
                panelResultado.add(movimientos[i][j]);
            }
        }
        panelResultado.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelResultado = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelResultadoLayout = new javax.swing.GroupLayout(panelResultado);
        panelResultado.setLayout(panelResultadoLayout);
        panelResultadoLayout.setHorizontalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        panelResultadoLayout.setVerticalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelResultado;
    // End of variables declaration//GEN-END:variables
}
